# Especialização em Inteligência Artificial – IFMG
# Trabalho da disciplina de Redes Neurais e Aprendizado Profundo
Autor: Alexandre Fortes Santana

Professor: Agnaldo José da Rocha Reis - UFOP

### 1. O que é inteligência para você?

Para mim, inteligência poderia ser definida pelos tópicos a seguir:
- Inteligência se manifesta em diferentes graus e tipos;
- Inteligência se desenvolve em um indivíduo, a princípio, biológico;
- O indivíduo detentor de inteligência em questão precisa ter a capacidade de memorizar informações em alguma escala;
- O indivíduo detentor de inteligência utiliza as informações a que tem acesso para interpretar o mundo a sua volta e a si mesmo;
- O indivíduo detentor de inteligência é capaz de decisões, agir e criar novos artefatos (imaginários ou físicos).

### 2. Em sua opinião, o que aconteceria se alguém descobrisse como implementar uma IA mais abrangente (e.g., AGI) em um robô?
A descoberta de uma Inteligência Artificial Geral seria um marco histórico para a humanidade. Experimentaríamos um período de frenesi nas redes sociais, nos noticiários e nas rodas de conversa. Muitos dilemas seriam discutidos, abordando temas como mercado de trabalho, impacto social, segurança, regulação, ética e questões militares. Os primeiros robôs focariam em demonstrar o potencial de suas aplicações e em realizar apresentações que alimentassem o frenesi público. Após um período marcado por medo, especulações e empolgação, veríamos as primeiras aplicações práticas direcionadas a problemas reais. Os primeiros robôs comerciais seriam mais simples, devido ao elevado custo de produção, e não necessariamente seriam humanoides. Não, não acredito que as máquinas se revoltariam, levando a um apocalipse.

### 3. Análise de um processo de destilação fracionada de petróleo
A partir da análise de um processo de destilação fracionada de petróleo observou-se que determinado óleo poderia ser classificado em duas classes de pureza {C1 e C2}, mediante a medição de três grandezas {x1, x2 e x3} que representam algumas das propriedades físico-químicas do óleo. Para tanto, pretende-se utilizar um perceptron para executar a classificação automática dessas duas classes. Assim, baseadas nas informações coletadas do processo, formou-se o conjunto de treinamento em anexo (vou te passar a estrutura de dados nas próximas mensagens), tomando por convenção o valor –1 para óleo pertencente à classe C1 e o valor +1 para óleo pertencente à classe C2.

**a. Execute dois treinamentos para a rede perceptron, inicializando-se o vetor de pesos em cada treinamento com valores aleatórios entre zero e um de tal forma que os elementos do vetor de pesos iniciais não sejam os mesmos.**

In [246]:
import numpy as np
import pandas as pd

data = np.loadtxt('tab_treinamento1.dat')
training_data = data[:, :3]
labels = data[:, 3]
#print(data)
#print(training_data)
#print(labels)

# Bias: Adicionando uma coluna de uns ao conjunto de dados de treinamento
training_data = np.c_[np.ones(training_data.shape[0]), training_data]

epochs = 1000
learning_rate = 0.1

# Inicialização de pesos
def initialize_weights(dim):
    return np.random.rand(dim)

# Treinamento do Perceptron
def train_perceptron(training_data, labels, learning_rate, epochs):
    # Inicialização de pesos
    weights = initialize_weights(training_data.shape[1])
    initial_weights = np.copy(weights)
    no_errors = 0
    final_epoch = 0
    
    for epoch in range(epochs):
        for i in range(len(training_data)):
            x = training_data[i]
            y = labels[i]
            
            # Cálculo do output e função de ativação
            output = np.dot(weights, x)
            prediction = 1 if output > 0 else -1

            #print("y:", y, "prediction:", prediction)

            # Atualização de pesos
            if prediction != y:
                weights += learning_rate * (y - prediction) * x
                no_errors += 1

        if no_errors == 0:
            final_epoch = epoch+1
            print(f"Convergiu na época {final_epoch}")
            break
        no_errors = 0 # reseta contador de erros
                
    return initial_weights, weights, final_epoch

# DataFrame para armazenar os resultados
results_df = pd.DataFrame(columns=["Treinamento", "Vetor de Pesos Inicial", "Vetor de Pesos Final", "Número de Épocas"])

# Executando Dois Treinamentos
for i in range(2):
    initial_weights, final_weights, final_epoch = train_perceptron(training_data, labels, learning_rate, epochs)  
    
    print(initial_weights)
    print(final_weights)
    print(final_epoch)

    new_row_df = pd.DataFrame({
        "Treinamento": f"T{i+1}",
        "Vetor de Pesos Inicial": initial_weights,
        "Vetor de Pesos Final": final_weights,
        "Número de Épocas": final_epoch
    })
    results_df = pd.concat([results_df, new_row_df], ignore_index=True)

results_df

Convergiu na época 433
[0.87132654 0.55759443 0.15687519 0.4031135 ]
[31.67132654 16.02395443 25.45669519 -7.5308065 ]
433
Convergiu na época 413
[0.46835909 0.13546439 0.47693809 0.48523506]
[31.06835909 15.60934439 25.07245809 -7.38660494]
413


Treinamento  Vetor de Pesos Inicial  Vetor de Pesos Final Número de Épocas
0          T1                0.871327             31.671327              433
1          T1                0.557594             16.023954              433
2          T1                0.156875             25.456695              433
3          T1                0.403114             -7.530806              433
4          T2                0.468359             31.068359              413
5          T2                0.135464             15.609344              413
6          T2                0.476938             25.072458              413
7          T2                0.485235             -7.386605              413

In [248]:
grouped = results_df.groupby("Treinamento")["Vetor de Pesos Final"].apply(list).reset_index()

weights_T1 = np.array(grouped[grouped["Treinamento"] == "T1"]["Vetor de Pesos Final"].iloc[0])
weights_T2 = np.array(grouped[grouped["Treinamento"] == "T2"]["Vetor de Pesos Final"].iloc[0])
#print(weights_T1)
#print(weights_T2)

[31.67132654 16.02395443 25.45669519 -7.5308065 ]
[31.06835909 15.60934439 25.07245809 -7.38660494]


**c. Após o treinamento do perceptron, aplique-o na classificação automática de novas amostras de óleo (ver arquivo tab_teste1.dat), indicando-se na tabela seguinte os resultados das saídas (Classes) referentes aos dois processos de treinamento realizados no item a.**

Para classificar novas amostras usando os pesos finais obtidos após o treinamento vamos criar uma função chamada classify_samples que receberá as novas amostras e os pesos finais.

In [258]:
new_samples = np.loadtxt('tab_teste1.dat')
results_df = pd.DataFrame(columns=["Amostra", "x1", "x2", "x3", "y (T1)", "y (T2)"])

# Função para classificar novas amostras
def classify_samples(samples, weights):
    predictions = np.sign(np.dot(samples, weights[1:]) + weights[0])  # Operação vetorizada
    return predictions

# Classificar novas amostras para cada treinamento e armazenar no DataFrame
all_predictions = []

trained_weights = [weights_T1, weights_T2]
print(trained_weights)

# Classificar novas amostras para cada treinamento
for i, weights in enumerate(trained_weights):
    predictions = classify_samples(new_samples, weights)
    print(f"Classificações usando o treinamento T{i+1}: {predictions}")

[[-0.3565  0.062   5.9891]
 [-0.7842  1.1267  5.5912]
 [ 0.3012  0.5611  5.8234]
 [ 0.7757  1.0648  8.0677]
 [ 0.157   0.8028  6.304 ]
 [-0.7014  1.0316  3.6005]
 [ 0.3748  0.1536  6.1537]
 [-0.692   0.9404  4.4058]
 [-1.397   0.7141  4.9263]
 [-1.8842 -0.2805  1.2548]]
[array([31.67132654, 16.02395443, 25.45669519, -7.5308065 ]), array([31.06835909, 15.60934439, 25.07245809, -7.38660494])]
Classificações usando o treinamento T1: [-1.  1.  1.  1.  1.  1. -1.  1. -1. -1.]
Classificações usando o treinamento T2: [-1.  1.  1.  1.  1.  1. -1.  1. -1. -1.]


**d. Explique por que o número de épocas de treinamento varia a cada vez que se executa o treinamento do perceptron.**  

Fatores como inicialização de pesos, ordem dos dados, taxa de aprendizado e critérios de convergência contribuem para a variação no número de épocas necessárias para treinar o modelo. No caso específico deste algorítmo, é devido à aleatoriedade dos pesos iniciais.

**e. Qual é a principal limitação do perceptron quando aplicado em problemas de classificação de padrões?**  

A maior limitação do Perceptron é sua incapacidade de resolver problemas que não são linearmente separáveis. Isso significa que se os dados não podem ser separados por uma única linha reta (em 2D), um plano (em 3D), ou um hiperplano (em mais de três dimensões), o Perceptron não será capaz de encontrar um conjunto de pesos que atinja zero erros no conjunto de treinamento.

Esta limitação foi uma das principais razões para o declínio inicial do interesse em redes neurais nos anos 60, especialmente após a publicação do livro "Perceptrons" por Marvin Minsky e Seymour Papert, que provou matematicamente essa limitação para o Perceptron de camada única.

Para solucionar problemas que não são linearmente separáveis, são necessárias estratégias mais complexas, como a inclusão de camadas ocultas para formar uma rede neural multicamadas (Multilayer Perceptron, MLP) e a aplicação de algoritmos de otimização mais sofisticados, como o backpropagation.

Além da limitação de só poder resolver problemas linearmente separáveis, o perceptron também tem outras limitações, como:

- Pode ser lento para treinar, especialmente para conjuntos de dados grandes;
- Pode ser instável, dependendo da inicialização dos pesos;
- Pode ser suscetível a overfitting.